import { defineConfig } from "vitepress";

// ---------- 中文侧边栏 ----------
const zhSidebarGuide = [
  {
    text: "入门",
    items: [{ text: "快速开始", link: "/guide/intro" }],
  },
  {
    text: "三维图层",
    items: [
      { text: "三维场景", link: "/guide/3d-scene" },
      { text: "矢量瓦片", link: "/guide/vector-tile" },
      { text: "gltf 模型", link: "/guide/gltf" },
      { text: "3dtiles", link: "/guide/3dtiles" },
      { text: "视频图层", link: "/guide/video" },
      { text: "WebGPU 渲染", link: "/guide/webgpu" },
    ],
  },
  {
    text: "样式指南",
    items: [
      { text: "样式指南", link: "/guide/style/intro" },
      { text: "Symbol 样式", link: "/guide/style/symbols" },
      { text: "材质", link: "/guide/style/material" },
      { text: "要素过滤", link: "/guide/style/feature-filter" },
      { text: "函数类型", link: "/guide/style/function-type" },
      {
        text: "渲染插件",
        collapsed: true,
        items: [
          { text: "icon", link: "/guide/style/plugin-icon" },
          { text: "text", link: "/guide/style/plugin-text" },
          { text: "line", link: "/guide/style/plugin-line" },
          { text: "line-gradient", link: "/guide/style/plugin-line-gradient" },
          { text: "fill", link: "/guide/style/plugin-fill" },
          { text: "native-line", link: "/guide/style/plugin-native-line" },
          { text: "native-point", link: "/guide/style/plugin-native-point" },
          { text: "lit", link: "/guide/style/plugin-lit" },
          { text: "phong", link: "/guide/style/plugin-phong" },
          { text: "wireframe", link: "/guide/style/plugin-wireframe" },
          { text: "tube", link: "/guide/style/plugin-tube" },
          { text: "heatmap", link: "/guide/style/plugin-heatmap" },
          { text: "billboard", link: "/guide/style/plugin-billboard" },
          { text: "terrain-flat-mask", link: "/guide/style/plugin-terrain-flat-mask" },
          { text: "gltf-lit", link: "/guide/style/plugin-gltf-lit" },
          { text: "gltf-phong", link: "/guide/style/plugin-gltf-phong" },
          { text: "water", link: "/guide/style/plugin-water" },
        ],
      },
    ],
  },
  {
    text: "交互与分析",
    items: [
      { text: "交互与事件", link: "/guide/interaction" },
      { text: "空间分析", link: "/guide/analysis" },
      { text: "数据", link: "/guide/data" },
      { text: "坐标系与投影", link: "/guide/projection" },
    ],
  },
];

const zhSidebarApi = [
  {
    text: "核心类",
    collapsed: false,
    items: [
      { text: "Map", link: "/api/map" },
      { text: "Layer", link: "/api/layer" },
      { text: "TileLayer", link: "/api/tile-layer" },
      { text: "OverlayLayer", link: "/api/overlay-layer" },
      { text: "VectorLayer", link: "/api/vector-layer" },
      { text: "Geometry", link: "/api/geometry" },
      { text: "Marker", link: "/api/marker" },
      { text: "Coordinate", link: "/api/coordinate" },
    ],
  },
  {
    text: "几何",
    collapsed: false,
    items: [
      { text: "Point", link: "/api/point" },
      { text: "LineString", link: "/api/line-string" },
      { text: "Polygon", link: "/api/polygon" },
      { text: "Ellipse", link: "/api/ellipse" },
      { text: "Rectangle", link: "/api/rectangle" },
      { text: "Sector", link: "/api/sector" },
      { text: "Circle", link: "/api/circle" },
      { text: "MultiPoint", link: "/api/multi-point" },
      { text: "MultiLineString", link: "/api/multi-line-string" },
      { text: "MultiPolygon", link: "/api/multi-polygon" },
      { text: "MultiGeometry", link: "/api/multi-geometry" },
      { text: "GeometryCollection", link: "/api/geometry-collection" },
      { text: "Path", link: "/api/path" },
      { text: "Curve", link: "/api/curve" },
      { text: "ArcCurve", link: "/api/arc-curve" },
      { text: "CubicBezierCurve", link: "/api/cubic-bezier-curve" },
      { text: "QuadBezierCurve", link: "/api/quad-bezier-curve" },
      { text: "ConnectorLine", link: "/api/connector-line" },
      { text: "ArcConnectorLine", link: "/api/arc-connector-line" },
      { text: "TextMarker", link: "/api/text-marker" },
      { text: "TextBox", link: "/api/text-box" },
      { text: "Label", link: "/api/label" },
      { text: "GeoJSON", link: "/api/geojson" },
      { text: "CenterMixin", link: "/api/center-mixin" },
      { text: "GeometryEditor", link: "/api/geometry-editor" },
    ],
  },
  {
    text: "图层",
    collapsed: true,
    items: [
      { text: "CanvasLayer", link: "/api/canvas-layer" },
      { text: "ImageLayer", link: "/api/image-layer" },
      { text: "ParticleLayer", link: "/api/particle-layer" },
      { text: "DrawToolLayer", link: "/api/draw-tool-layer" },
      { text: "GroupTileLayer", link: "/api/group-tile-layer" },
      { text: "WMSTileLayer", link: "/api/wms-tile-layer" },
      { text: "TileSystem", link: "/api/tile-system" },
    ],
  },
  {
    text: "基础类",
    collapsed: true,
    items: [
      { text: "Class", link: "/api/class" },
      { text: "Eventable", link: "/api/eventable" },
      { text: "JSONAble", link: "/api/json-able" },
      { text: "Handler", link: "/api/handler" },
      { text: "Handlerable", link: "/api/handlerable" },
      { text: "Renderable", link: "/api/renderable" },
      { text: "Ajax", link: "/api/ajax" },
    ],
  },
  {
    text: "Geo 值类型",
    collapsed: true,
    items: [
      { text: "Extent", link: "/api/extent" },
      { text: "PointExtent", link: "/api/point-extent" },
      { text: "Position", link: "/api/position" },
      { text: "Size", link: "/api/size" },
      { text: "CRS", link: "/api/crs" },
      { text: "Transformation", link: "/api/transformation" },
    ],
  },
  {
    text: "地图工具",
    collapsed: true,
    items: [
      { text: "MapTool", link: "/api/map-tool" },
      { text: "DrawTool", link: "/api/draw-tool" },
      { text: "AreaTool", link: "/api/area-tool" },
      { text: "DistanceTool", link: "/api/distance-tool" },
    ],
  },
  {
    text: "UI 组件",
    collapsed: true,
    items: [
      { text: "UIComponent", link: "/api/ui-component" },
      { text: "UIMarker", link: "/api/ui-marker" },
      { text: "InfoWindow", link: "/api/info-window" },
      { text: "Menu", link: "/api/menu" },
      { text: "Menuable", link: "/api/menuable" },
      { text: "ToolTip", link: "/api/tool-tip" },
    ],
  },
  {
    text: "动画",
    collapsed: true,
    items: [
      { text: "Animation", link: "/api/animation-animation" },
      { text: "Player", link: "/api/animation-player" },
      { text: "Easing", link: "/api/animation-easing" },
      { text: "Frame", link: "/api/animation-frame" },
    ],
  },
  {
    text: "控件",
    collapsed: true,
    items: [
      { text: "Control", link: "/api/control" },
      { text: "Attribution", link: "/api/control-attribution" },
      { text: "Zoom", link: "/api/control-zoom" },
      { text: "Scale", link: "/api/control-scale" },
      { text: "Overview", link: "/api/control-overview" },
      { text: "Toolbar", link: "/api/control-toolbar" },
      { text: "Panel", link: "/api/control-panel" },
      { text: "LayerSwitcher", link: "/api/control-layer-switcher" },
      { text: "Compass", link: "/api/control-compass" },
      { text: "Nav", link: "/api/control-nav" },
      { text: "Reset", link: "/api/control-reset" },
    ],
  },
  {
    text: "投影",
    collapsed: true,
    items: [
      { text: "projection.Common", link: "/api/projection-common" },
      { text: "projection.EPSG3857", link: "/api/projection-epsg3857" },
      { text: "projection.EPSG4326", link: "/api/projection-epsg4326" },
      { text: "projection.EPSG9807", link: "/api/projection-epsg9807" },
      { text: "projection.IDENTITY", link: "/api/projection-identity" },
      { text: "projection.BAIDU", link: "/api/projection-baidu" },
      { text: "projection.UTM", link: "/api/projection-utm" },
    ],
  },
  {
    text: "测量器",
    collapsed: true,
    items: [
      { text: "measurer.Measurer", link: "/api/measurer-measurer" },
      { text: "measurer.Common", link: "/api/measurer-common" },
      { text: "measurer.Identity", link: "/api/measurer-identity" },
      { text: "measurer.WGS84Sphere", link: "/api/measurer-wgs84sphere" },
      { text: "measurer.BaiduSphere", link: "/api/measurer-baidusphere" },
    ],
  },
  {
    text: "渲染器",
    collapsed: true,
    items: [
      { text: "CanvasRenderer", link: "/api/canvas-renderer" },
    ],
  },
  {
    text: "工具函数",
    collapsed: true,
    items: [
      { text: "Util", link: "/api/util" },
      { text: "DomUtil", link: "/api/dom-util" },
      { text: "StringUtil", link: "/api/string-util" },
    ],
  },
  {
    text: "矢量瓦片图层",
    collapsed: false,
    items: [
      { text: "VectorTileLayer", link: "/api/vector-tile-layer" },
      { text: "GeoJSONVectorTileLayer", link: "/api/geojson-vector-tile-layer" },
      { text: "PointLayer", link: "/api/point-layer" },
      { text: "LineStringLayer", link: "/api/line-string-layer" },
      { text: "PolygonLayer", link: "/api/polygon-layer" },
      { text: "ExtrudePolygonLayer", link: "/api/extrude-polygon-layer" },
    ],
  },
  {
    text: "三维场景与模型",
    collapsed: false,
    items: [
      { text: "GroupGLLayer", link: "/api/group-gl-layer" },
      { text: "Geo3DTilesLayer", link: "/api/geo-3dtiles-layer" },
      { text: "GLTFLayer", link: "/api/gltf-layer" },
      { text: "GLTFMarker", link: "/api/gltf-marker" },
      { text: "MultiGLTFMarker", link: "/api/multi-gltf-marker" },
    ],
  },
  {
    text: "空间分析",
    collapsed: false,
    items: [
      { text: "Analysis", link: "/api/analysis" },
      { text: "CutAnalysis", link: "/api/cut-analysis" },
      { text: "ExcavateAnalysis", link: "/api/excavate-analysis" },
      { text: "CrossCutAnalysis", link: "/api/crosscut-analysis" },
      { text: "FloodAnalysis", link: "/api/flood-analysis" },
      { text: "HeightLimitAnalysis", link: "/api/height-limit-analysis" },
      { text: "InSightAnalysis", link: "/api/insight-analysis" },
      { text: "SkylineAnalysis", link: "/api/skyline-analysis" },
      { text: "ViewshedAnalysis", link: "/api/viewshed-analysis" },
    ],
  },
  {
    text: "参考",
    collapsed: true,
    items: [
      { text: "矢量瓦片简介", link: "/api/vt-intro" },
      { text: "图层对比", link: "/api/vt-compare" },
      { text: "性能优化", link: "/api/vt-performance" },
    ],
  },
];

// ---------- 英文侧边栏 ----------
const enSidebarGuide = [
  {
    text: "Getting Started",
    items: [{ text: "Quick Start", link: "/en/guide/intro" }],
  },
  {
    text: "3D Layers",
    items: [
      { text: "3D Scene", link: "/en/guide/3d-scene" },
      { text: "Vector Tiles", link: "/en/guide/vector-tile" },
      { text: "gltf Models", link: "/en/guide/gltf" },
      { text: "3dtiles", link: "/en/guide/3dtiles" },
      { text: "Video Layer", link: "/en/guide/video" },
      { text: "WebGPU Rendering", link: "/en/guide/webgpu" },
    ],
  },
  {
    text: "Style Guide",
    items: [
      { text: "Style Guide", link: "/en/guide/style/intro" },
      { text: "Symbol Styles", link: "/en/guide/style/symbols" },
      { text: "Materials", link: "/en/guide/style/material" },
      { text: "Feature Filters", link: "/en/guide/style/feature-filter" },
      { text: "Function Types", link: "/en/guide/style/function-type" },
      {
        text: "Rendering Plugins",
        collapsed: true,
        items: [
          { text: "icon", link: "/en/guide/style/plugin-icon" },
          { text: "text", link: "/en/guide/style/plugin-text" },
          { text: "line", link: "/en/guide/style/plugin-line" },
          { text: "line-gradient", link: "/en/guide/style/plugin-line-gradient" },
          { text: "fill", link: "/en/guide/style/plugin-fill" },
          { text: "native-line", link: "/en/guide/style/plugin-native-line" },
          { text: "native-point", link: "/en/guide/style/plugin-native-point" },
          { text: "lit", link: "/en/guide/style/plugin-lit" },
          { text: "phong", link: "/en/guide/style/plugin-phong" },
          { text: "wireframe", link: "/en/guide/style/plugin-wireframe" },
          { text: "tube", link: "/en/guide/style/plugin-tube" },
          { text: "heatmap", link: "/en/guide/style/plugin-heatmap" },
          { text: "billboard", link: "/en/guide/style/plugin-billboard" },
          { text: "terrain-flat-mask", link: "/en/guide/style/plugin-terrain-flat-mask" },
          { text: "gltf-lit", link: "/en/guide/style/plugin-gltf-lit" },
          { text: "gltf-phong", link: "/en/guide/style/plugin-gltf-phong" },
          { text: "water", link: "/en/guide/style/plugin-water" },
        ],
      },
    ],
  },
  {
    text: "Interaction & Analysis",
    items: [
      { text: "Interaction & Events", link: "/en/guide/interaction" },
      { text: "Spatial Analysis", link: "/en/guide/analysis" },
      { text: "Data", link: "/en/guide/data" },
      { text: "Projection & Coordinates", link: "/en/guide/projection" },
    ],
  },
];

const enSidebarApi = [
  {
    text: "Core Classes",
    collapsed: false,
    items: [
      { text: "Map", link: "/en/api/map" },
      { text: "Layer", link: "/en/api/layer" },
      { text: "TileLayer", link: "/en/api/tile-layer" },
      { text: "OverlayLayer", link: "/en/api/overlay-layer" },
      { text: "VectorLayer", link: "/en/api/vector-layer" },
      { text: "Geometry", link: "/en/api/geometry" },
      { text: "Marker", link: "/en/api/marker" },
      { text: "Coordinate", link: "/en/api/coordinate" },
    ],
  },
  {
    text: "Geometry",
    collapsed: false,
    items: [
      { text: "Point", link: "/en/api/point" },
      { text: "LineString", link: "/en/api/line-string" },
      { text: "Polygon", link: "/en/api/polygon" },
      { text: "Ellipse", link: "/en/api/ellipse" },
      { text: "Rectangle", link: "/en/api/rectangle" },
      { text: "Sector", link: "/en/api/sector" },
      { text: "Circle", link: "/en/api/circle" },
      { text: "MultiPoint", link: "/en/api/multi-point" },
      { text: "MultiLineString", link: "/en/api/multi-line-string" },
      { text: "MultiPolygon", link: "/en/api/multi-polygon" },
      { text: "MultiGeometry", link: "/en/api/multi-geometry" },
      { text: "GeometryCollection", link: "/en/api/geometry-collection" },
      { text: "Path", link: "/en/api/path" },
      { text: "Curve", link: "/en/api/curve" },
      { text: "ArcCurve", link: "/en/api/arc-curve" },
      { text: "CubicBezierCurve", link: "/en/api/cubic-bezier-curve" },
      { text: "QuadBezierCurve", link: "/en/api/quad-bezier-curve" },
      { text: "ConnectorLine", link: "/en/api/connector-line" },
      { text: "ArcConnectorLine", link: "/en/api/arc-connector-line" },
      { text: "TextMarker", link: "/en/api/text-marker" },
      { text: "TextBox", link: "/en/api/text-box" },
      { text: "Label", link: "/en/api/label" },
      { text: "GeoJSON", link: "/en/api/geojson" },
      { text: "CenterMixin", link: "/en/api/center-mixin" },
      { text: "GeometryEditor", link: "/en/api/geometry-editor" },
    ],
  },
  {
    text: "Layers",
    collapsed: true,
    items: [
      { text: "CanvasLayer", link: "/en/api/canvas-layer" },
      { text: "ImageLayer", link: "/en/api/image-layer" },
      { text: "ParticleLayer", link: "/en/api/particle-layer" },
      { text: "DrawToolLayer", link: "/en/api/draw-tool-layer" },
      { text: "GroupTileLayer", link: "/en/api/group-tile-layer" },
      { text: "WMSTileLayer", link: "/en/api/wms-tile-layer" },
      { text: "TileSystem", link: "/en/api/tile-system" },
    ],
  },
  {
    text: "Base Classes",
    collapsed: true,
    items: [
      { text: "Class", link: "/en/api/class" },
      { text: "Eventable", link: "/en/api/eventable" },
      { text: "JSONAble", link: "/en/api/json-able" },
      { text: "Handler", link: "/en/api/handler" },
      { text: "Handlerable", link: "/en/api/handlerable" },
      { text: "Renderable", link: "/en/api/renderable" },
      { text: "Ajax", link: "/en/api/ajax" },
    ],
  },
  {
    text: "Geo Types",
    collapsed: true,
    items: [
      { text: "Extent", link: "/en/api/extent" },
      { text: "PointExtent", link: "/en/api/point-extent" },
      { text: "Position", link: "/en/api/position" },
      { text: "Size", link: "/en/api/size" },
      { text: "CRS", link: "/en/api/crs" },
      { text: "Transformation", link: "/en/api/transformation" },
    ],
  },
  {
    text: "Map Tools",
    collapsed: true,
    items: [
      { text: "MapTool", link: "/en/api/map-tool" },
      { text: "DrawTool", link: "/en/api/draw-tool" },
      { text: "AreaTool", link: "/en/api/area-tool" },
      { text: "DistanceTool", link: "/en/api/distance-tool" },
    ],
  },
  {
    text: "UI Components",
    collapsed: true,
    items: [
      { text: "UIComponent", link: "/en/api/ui-component" },
      { text: "UIMarker", link: "/en/api/ui-marker" },
      { text: "InfoWindow", link: "/en/api/info-window" },
      { text: "Menu", link: "/en/api/menu" },
      { text: "Menuable", link: "/en/api/menuable" },
      { text: "ToolTip", link: "/en/api/tool-tip" },
    ],
  },
  {
    text: "Animation",
    collapsed: true,
    items: [
      { text: "Animation", link: "/en/api/animation-animation" },
      { text: "Player", link: "/en/api/animation-player" },
      { text: "Easing", link: "/en/api/animation-easing" },
      { text: "Frame", link: "/en/api/animation-frame" },
    ],
  },
  {
    text: "Controls",
    collapsed: true,
    items: [
      { text: "Control", link: "/en/api/control" },
      { text: "Attribution", link: "/en/api/control-attribution" },
      { text: "Zoom", link: "/en/api/control-zoom" },
      { text: "Scale", link: "/en/api/control-scale" },
      { text: "Overview", link: "/en/api/control-overview" },
      { text: "Toolbar", link: "/en/api/control-toolbar" },
      { text: "Panel", link: "/en/api/control-panel" },
      { text: "LayerSwitcher", link: "/en/api/control-layer-switcher" },
      { text: "Compass", link: "/en/api/control-compass" },
      { text: "Nav", link: "/en/api/control-nav" },
      { text: "Reset", link: "/en/api/control-reset" },
    ],
  },
  {
    text: "Projection",
    collapsed: true,
    items: [
      { text: "projection.Common", link: "/en/api/projection-common" },
      { text: "projection.EPSG3857", link: "/en/api/projection-epsg3857" },
      { text: "projection.EPSG4326", link: "/en/api/projection-epsg4326" },
      { text: "projection.EPSG9807", link: "/en/api/projection-epsg9807" },
      { text: "projection.IDENTITY", link: "/en/api/projection-identity" },
      { text: "projection.BAIDU", link: "/en/api/projection-baidu" },
      { text: "projection.UTM", link: "/en/api/projection-utm" },
    ],
  },
  {
    text: "Measurer",
    collapsed: true,
    items: [
      { text: "measurer.Measurer", link: "/en/api/measurer-measurer" },
      { text: "measurer.Common", link: "/en/api/measurer-common" },
      { text: "measurer.Identity", link: "/en/api/measurer-identity" },
      { text: "measurer.WGS84Sphere", link: "/en/api/measurer-wgs84sphere" },
      { text: "measurer.BaiduSphere", link: "/en/api/measurer-baidusphere" },
    ],
  },
  {
    text: "Renderer",
    collapsed: true,
    items: [
      { text: "CanvasRenderer", link: "/en/api/canvas-renderer" },
    ],
  },
  {
    text: "Utils",
    collapsed: true,
    items: [
      { text: "Util", link: "/en/api/util" },
      { text: "DomUtil", link: "/en/api/dom-util" },
      { text: "StringUtil", link: "/en/api/string-util" },
    ],
  },
  {
    text: "Vector Tile Layers",
    collapsed: false,
    items: [
      { text: "VectorTileLayer", link: "/en/api/vector-tile-layer" },
      { text: "GeoJSONVectorTileLayer", link: "/en/api/geojson-vector-tile-layer" },
      { text: "PointLayer", link: "/en/api/point-layer" },
      { text: "LineStringLayer", link: "/en/api/line-string-layer" },
      { text: "PolygonLayer", link: "/en/api/polygon-layer" },
      { text: "ExtrudePolygonLayer", link: "/en/api/extrude-polygon-layer" },
    ],
  },
  {
    text: "3D Scenes & Models",
    collapsed: false,
    items: [
      { text: "GroupGLLayer", link: "/en/api/group-gl-layer" },
      { text: "Geo3DTilesLayer", link: "/en/api/geo-3dtiles-layer" },
      { text: "GLTFLayer", link: "/en/api/gltf-layer" },
      { text: "GLTFMarker", link: "/en/api/gltf-marker" },
      { text: "MultiGLTFMarker", link: "/en/api/multi-gltf-marker" },
    ],
  },
  {
    text: "Spatial Analysis",
    collapsed: false,
    items: [
      { text: "Analysis", link: "/en/api/analysis" },
      { text: "CutAnalysis", link: "/en/api/cut-analysis" },
      { text: "ExcavateAnalysis", link: "/en/api/excavate-analysis" },
      { text: "CrossCutAnalysis", link: "/en/api/crosscut-analysis" },
      { text: "FloodAnalysis", link: "/en/api/flood-analysis" },
      { text: "HeightLimitAnalysis", link: "/en/api/height-limit-analysis" },
      { text: "InSightAnalysis", link: "/en/api/insight-analysis" },
      { text: "SkylineAnalysis", link: "/en/api/skyline-analysis" },
      { text: "ViewshedAnalysis", link: "/en/api/viewshed-analysis" },
    ],
  },
  {
    text: "References",
    collapsed: true,
    items: [
      { text: "Vector Tile Intro", link: "/en/api/vt-intro" },
      { text: "Layer Comparison", link: "/en/api/vt-compare" },
      { text: "Performance", link: "/en/api/vt-performance" },
    ],
  },
];

export default defineConfig({
  title: "maptalks",
  description: "maptalks 新引擎文档",
  srcDir: "docs",
  vite: {
    // docs/public/examples 下的示例 HTML 在浏览器里通过 REPL 的 import map 解析
    // maptalks/gl-layers 等裸导入（CDN），不应被 Vite optimizeDeps 当作本地依赖预打包。
    optimizeDeps: {
      exclude: [
        "maptalks",
        "gl-layers",
        "mt.gui",
        "draco",
        "proj4",
        "maptalks-gl",
      ],
    },
  },
  locales: {
    root: {
      label: "简体中文",
      lang: "zh-CN",
      themeConfig: {
        nav: [
          { text: "首页", link: "/" },
          { text: "指南", link: "/guide/intro" },
          { text: "API", link: "/api/vector-tile-layer" },
          { text: "示例", link: "/examples/" },
        ],
        sidebar: {
          "/guide/": zhSidebarGuide,
          "/api/": zhSidebarApi,
        },
      },
    },
    en: {
      label: "English",
      lang: "en-US",
      themeConfig: {
        nav: [
          { text: "Home", link: "/en/" },
          { text: "Guide", link: "/en/guide/intro" },
          { text: "API", link: "/en/api/vector-tile-layer" },
          { text: "Examples", link: "/en/examples/" },
        ],
        sidebar: {
          "/en/guide/": enSidebarGuide,
          "/en/api/": enSidebarApi,
        },
      },
    },
  },
});
